# Generated by Django 5.0.2 on 2024-02-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSerch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_licitacao', models.TextField()),
                ('n_certame', models.TextField()),
                ('atividade', models.TextField()),
                ('modalidade', models.TextField()),
                ('comprador', models.TextField()),
                ('descricao', models.TextField()),
                ('unidade', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
